// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbeE8Wl95a8jY6qVqjsfyXZq673XhXWJs',
    appId: '1:1017791454388:web:7bb3841bccdfb90fb2cbe1',
    messagingSenderId: '1017791454388',
    projectId: 'red-cell-12a75',
    authDomain: 'red-cell-12a75.firebaseapp.com',
    storageBucket: 'red-cell-12a75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWaXCuUzkJ9evf_nproIPoZx4YFCd5PDk',
    appId: '1:1017791454388:android:8b8bdd16de839d32b2cbe1',
    messagingSenderId: '1017791454388',
    projectId: 'red-cell-12a75',
    storageBucket: 'red-cell-12a75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOJ-6K5wQ15vB6F1l0UVyf8bmpIV9nw88',
    appId: '1:1017791454388:ios:1b1b27eb8c8eb422b2cbe1',
    messagingSenderId: '1017791454388',
    projectId: 'red-cell-12a75',
    storageBucket: 'red-cell-12a75.firebasestorage.app',
    iosBundleId: 'com.example.redCell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOJ-6K5wQ15vB6F1l0UVyf8bmpIV9nw88',
    appId: '1:1017791454388:ios:1b1b27eb8c8eb422b2cbe1',
    messagingSenderId: '1017791454388',
    projectId: 'red-cell-12a75',
    storageBucket: 'red-cell-12a75.firebasestorage.app',
    iosBundleId: 'com.example.redCell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbeE8Wl95a8jY6qVqjsfyXZq673XhXWJs',
    appId: '1:1017791454388:web:9ecc991f10ce188eb2cbe1',
    messagingSenderId: '1017791454388',
    projectId: 'red-cell-12a75',
    authDomain: 'red-cell-12a75.firebaseapp.com',
    storageBucket: 'red-cell-12a75.firebasestorage.app',
  );
}
